name: Deploy CDN

on:
  push:
    branches:
      - main
    paths:
      - 'cdn/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy
        run: |
          cd cdn
          echo "Deploying package-a (add your deployment logic here)"
          npm run build
          npm run deploy
