name: CI/CD

on:
  push:
    branches: [main]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx nx affected --target=test --parallel --max-parallel=3
      - run: npx nx affected --target=build --parallel --max-parallel=3
      - run: npx nx affected --target=deploy --parallel --max-parallel=3
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Commit Version Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add libs/*/package.json
          git commit -m "chore: update versions [skip ci]" || echo "No changes"
          git push
